version: '3.4'

services:

  nav_client:
    container_name: nav_client
    env_file: .env
    # user: ${CURRENT_UID}
    build:
      context: ./nav_client
    volumes:
      - ./nav_client:/app
    restart: on-failure
    ports:
      - 80:80
    networks:
      private_network:

  xlsx_service:
    container_name: xlsx_service
    env_file: .env
    user: ${CURRENT_UID}
    build:
      context: ./xlsx_service
    volumes:
      - ./xlsx_service:/app
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      private_network:

  dashboard:
    container_name: dashboard
    env_file: .env
    user: ${CURRENT_UID}
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/app
    restart: on-failure
    depends_on:
      - nav_client
      - xlsx_service
    ports:
      - 8050:8050
    networks:
      private_network:


networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
