version: '3.4'

services:

  client:
    container_name: nav_client
    env_file: .env
    user: ${CURRENT_UID}
    build:
      context: ./nav_client
    volumes:
      - ./nav_client:/app
    restart: on-failure
    networks:
      private_network:

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
