name: Xeon prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp /route-log/_config/.env ./.env
      - name: Fix docker-compose
        run: | 
          rm -f ./docker-compose.yml
          cp /route-log/_config/docker-compose.yml ./docker-compose.yml
#       - name: Correct nginx._config
#         run: |
#           rm -f ./nginx.conf
#           cp /route-log/_config/nginx.conf ./nginx.conf
      - name: Generate frontend .env
        run: cp /route-log/_config/.env ./frontend/.env
      - name: Create volumes
        run: |
          docker volume create route_log_db_data
          docker volume create route_log_media
      - name: Make upb
        run: make upb
      - name: Build frontend
        run: |
          docker run -i route-log_frontend cp -rf /app/dist/ /app/build/
