name: clrn stage CI

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp /opt/containers/route-log/.env ./.env
      - name: Create volumes
        run: |
          docker volume create route_log_db_data
          docker volume create route_log_media
      - name: Fix docker-compose.yml
        run: |
          rm ./docker-compose.yml
          cp /opt/containers/route-log/docker-compose.yml ./docker-compose.yml
      - name: Make upb
        run: make upb
